-- ACTIVEZ L'EXTENSION AUTH (automatique sur Supabase) --

-- 1. Table des Catégories
create table public.categories (
  id bigint generated by default as identity primary key,
  code text unique not null,
  libelle text not null
);

-- 2. Table du Matériel
create table public.materiels (
  id bigint generated by default as identity primary key,
  numero_inventaire text unique not null,
  categorie_id bigint references public.categories(id),
  nom text not null,
  marque text,
  modele text,
  numero_serie text,
  date_acquisition date,
  service text,
  statut text default 'En service',
  commentaires text,
  created_at timestamptz default now()
);

-- 3. Table des Campagnes d'Inventaire
create table public.inventaires (
  id bigint generated by default as identity primary key,
  nom text not null,
  service_perimetre text,
  date_debut date,
  statut text default 'En cours',
  created_at timestamptz default now()
);

-- 4. Table des Lignes d'Inventaire (Resultats Scan)
create table public.inventaire_lignes (
  id bigint generated by default as identity primary key,
  inventaire_id bigint references public.inventaires(id),
  materiel_id bigint references public.materiels(id),
  scanne_par uuid references auth.users(id), -- Lien avec l'utilisateur connecté
  date_scan timestamptz default now(),
  presence boolean default true,
  commentaire text
);

-- 5. Profils Utilisateurs (Gestion des Rôles)
create table public.profiles (
  id uuid references auth.users(id) primary key,
  email text,
  role text default 'agent' check (role in ('admin', 'agent'))
);

-- Données initiales (Catégories)
insert into public.categories (code, libelle) values 
('INF', 'Matériel Informatique'),
('BUR', 'Matériel Bureautique'),
('MED', 'Matériel Médical');

-- Function to handle new user
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, role)
  values (new.id, new.email, 'agent');
  return new;
end;
$$ language plpgsql security definer;

-- Trigger the function every time a user is created
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();


-- RLS Setup
alter table public.profiles enable row level security;
alter table public.categories enable row level security;
alter table public.materiels enable row level security;
alter table public.inventaires enable row level security;
alter table public.inventaire_lignes enable row level security;

create policy "Public profiles are viewable by everyone." on profiles for select using (true);
create policy "Users can insert their own profile." on profiles for insert with check (auth.uid() = id);
create policy "Users can update own profile." on profiles for update using (auth.uid() = id);

create policy "Categories are viewable by everyone." on categories for select using (true);
create policy "Materiels are viewable by everyone." on materiels for select using (true);
create policy "Inventaires are viewable by everyone." on inventaires for select using (true);
create policy "Lignes are viewable by everyone." on inventaire_lignes for select using (true);

-- Insert policies (Need to restrict to Admin later, but open for now for simplicity or specific logic)
create policy "Authenticated can insert inventaire_lignes" on inventaire_lignes for insert with check (auth.role() = 'authenticated');
create policy "Authenticated can insert materiels" on materiels for insert with check (auth.role() = 'authenticated');
create policy "Authenticated can insert inventaires" on inventaires for insert with check (auth.role() = 'authenticated');
